
import React from 'react';
import type { Metadata } from 'next';
import BlogPostClient from './blog-post-client';
import { getSocialPostByIdAction } from '@/app/actions/social-media-actions';
import { notFound } from 'next/navigation';

export async function generateMetadata({ params }: { params: Promise<{ postId: string }> }): Promise<Metadata> {
  const { postId } = await params;
  
  const result = await getSocialPostByIdAction(postId);
  
  if (!result.success || !result.data) {
    return {
      title: 'Content Not Found',
      description: 'The requested content could not be found',
    };
  }

  const post = result.data;
  const pageTitle = post.originalTopic || 'OmniFlow Content';
  const pageDescription = post.textContent?.substring(0, 160).replace(/<[^>]*>/g, '') || 'View content generated by OmniFlow';
  const ogImage = post.imageUrl || 'https://placehold.co/1200x630.png';

  return {
    title: pageTitle,
    description: pageDescription,
    openGraph: {
        title: pageTitle,
        description: pageDescription,
        images: [
            {
                url: ogImage,
                width: 1200,
                height: 630,
                alt: pageTitle,
            },
        ],
        type: 'article',
    },
    twitter: {
        card: 'summary_large_image',
        title: pageTitle,
        description: pageDescription,
        images: [ogImage],
    },
  };
}

export default async function BlogPostPage({ params }: { params: Promise<{ postId: string }> }) {
  const { postId } = await params;
  
  const result = await getSocialPostByIdAction(postId);
  
  if (!result.success || !result.data) {
    notFound();
  }

  return <BlogPostClient post={result.data} />;
}
